# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/nirnanaaa/kube-readiness
    steps:
      - run: curl -sL# https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.0.0-rc.0/kubebuilder_2.0.0-rc.0_linux_amd64.tar.gz | tar -xz -C /tmp
      - run: sudo mkdir -p /usr/local/kubebuilder/
      - run: sudo mv /tmp/kubebuilder_2.0.0-rc.0_linux_amd64/bin /usr/local/kubebuilder/bin
      - checkout
      - run: make test
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
      - run: docker build -t fkconsultin/kube-readiness:$(git describe --abbrev=1 --tags --always) .
      - run: docker push fkconsultin/kube-readiness:$(git describe --abbrev=1 --tags --always)
      - run: docker tag fkconsultin/kube-readiness:$(git describe --abbrev=1 --tags --always) fkconsultin/kube-readiness:latest
      - run: docker push fkconsultin/kube-readiness:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build