apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-readiness.fullname" . }}
  labels:
    {{- include "kube-readiness.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-readiness.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-readiness.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kube-readiness.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- if .Values.region }}
          - --aws-region={{ .Values.region }}
          {{- end }}
          {{- if .Values.awsAssumeRoleArn }}
          - --aws-assume-role-arn={{ .Values.awsAssumeRoleArn }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
